// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPBASE_URL = import.meta.env.VITE_SUPBASE_URL;
const SUPBASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPBASE_PUBLISHABLE_KEY;

// Validate environment variables
if (!SUPBASE_URL || !SUPBASE_PUBLISHABLE_KEY) {
  const missing = [];
  if (!SUPBASE_URL) missing.push('VITE_SUPBASE_URL');
  if (!SUPBASE_PUBLISHABLE_KEY) missing.push('VITE_SUPBASE_PUBLISHABLE_KEY');
  
  console.error('❌ Missing Supabase environment variables:', missing.join(', '));
  console.error('Please set these variables in Railway: Variables tab → Add Variable');
  
  // Create a placeholder client to prevent app crash
  // The app will show an error message instead
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPBASE_URL || 'https://placeholder.supabase.co',
  SUPBASE_PUBLISHABLE_KEY || 'placeholder-key',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);